server:
  port: 8081
  servlet:
    context-path: "/policy"
spring:
  datasource:
    url: jdbc:postgresql://luz-del-alba.eastus.cloudapp.azure.com:5432/customer
    username: root
    password: password
    driverClassName: org.postgresql.Driver
    platform: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        ddl-auto: update
        temp:
          use_jdbc_metadata_defaults: false